### ISSUE TITLE
Druxt Office Hours - 21/12/08

### ISSUE THREAD

**Issue by Decipher** [druxt/druxt.js#396]
# Druxt Office Hours

Wednesday is Druxt Office Hours, where contributors are available between 9:00-17:00 AEDT on Discord: https://discord.druxtjs.org (#get-involved)

## Topic

Better Views routes, pagination and filtering.

**Task list**
- Improvements:
  - [ ] Update Umami install profile Views: https://www.drupal.org/project/drupal/issues/3253159
    - [ ] https://github.com/druxt/demo-api.druxtjs.org/issues/57
  - [x] #397 
  - [ ] #398
  - [ ] #399
  - [ ] #115
  - [ ] #357 
  - [ ] #293 
  - [ ] #279

- Documentation:
  - [ ] #387
  - [ ] #330
  - [ ] #198
    - [ ] #335
  - [ ] #197 

- Experiments:
  - [ ] https://github.com/Decipher/druxt-experiments/issues/2

**Getting started**
The Druxt Git repository is setup with [GitPod](https://gitpod.io) integration, all you need to do is open the following link, sign in or up (free, authentication with GitHub), and GitPod will set up your Druxt development environment:

https://gitpod.io#github.com/druxt/druxt.js

**Comment by Decipher** [comment]
#397 is an amazing improvement, improves the entire experience of Druxt, and appears to be faster to render.
