### ISSUE TITLE
Druxt Office Hours - 22/02/09

### ISSUE THREAD

**Issue by Decipher** [druxt/druxt.js#440]
# Druxt Office Hours

Wednesday is Druxt Office Hours, where contributors are available between 9:00-17:00 AEDT on Discord: https://discord.druxtjs.org (#get-involved)

## Topic

This week the focus, and the coming weeks, will be on the following three features; Node preview, Multilingual and Authentication.

**Task list**
- Improvements:
  - [ ] #158 
  - [ ] #63
  - [ ] #21
  - [ ] #293 
  - [ ] #307
  - [ ] #97

- Documentation: 
  - [ ] #198
  - [ ] #387
  - [ ] #423
  - [ ] #197 
  - [ ] #330

- Experiments:
  - [x] https://github.com/Decipher/druxt-experiments/issues/10
    - [x] https://github.com/Decipher/druxt-experiments/tree/feature/node_preview 
  - [ ] #334
    - [ ] https://github.com/Decipher/druxt-experiments/issues/7
    - [ ] https://github.com/Decipher/druxt-experiments/tree/feature/webform

**Getting started**
The Druxt Git repository is setup with [GitPod](https://gitpod.io) integration, all you need to do is open the following link, sign in or up (free, authentication with GitHub), and GitPod will set up your Druxt development environment:

https://gitpod.io#github.com/druxt/druxt.js
