### ISSUE TITLE
Druxt Office Hours - 04/05/22

### ISSUE THREAD

**Issue by Decipher** [druxt/druxt.js#494]
# Druxt Office Hours

Wednesday is Druxt Office Hours, where contributors are available between 09:00-17:00 AEDT (22:00-06:00 UTC) on Discord: https://discord.druxtjs.org (#get-involved)

## Topic

The focus for this week will be continued development on Multilingual support for all core modules, as well as making a push forwards with documentation.

Have an issue you want prioritised? Comment below, or let us know on Discord.

### Development:

- [ ] #158 ***required for 1.0.0 release**
  - [x] Update automated tests to reflect changes
- [ ] #307

### Documentation: 

- [ ] #197 
- [ ] https://github.com/druxt/cms.druxtjs.org/issues/16
  - [ ] #172
- [ ] #198
  - [ ] #387
- [ ] #330

Find more documentation issues @ https://github.com/druxt/druxt.js/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation

### Support / Bug fixes:

- [ ] #464 ***Try with Nuxt Storybook 4.3.1**
- [ ] #442 ***Windows only bug**

### Experiments

- [ ] OAuth2 Password flow
- [ ] #476 

## Getting started

The Druxt Git repository is setup with [GitPod](https://gitpod.io) integration, all you need to do is open the following link, sign in or up (free, authentication with GitHub), and GitPod will set up your Druxt development environment:

https://gitpod.io#github.com/druxt/druxt.js
