### ISSUE TITLE
Druxt Office Hours - 22/07/06

### ISSUE THREAD

**Issue by Decipher** [druxt/druxt.js#529]
# Druxt Office Hours

Wednesday is Druxt Office Hours, where contributors are available between 09:00-17:00 AEST (23:00-07:00 UTC) on Discord: https://discord.druxtjs.org (#get-involved)

## Topic

This week will focus on any outstanding bugs and making improvements to the documentation in preparation for a 1.0.0 release.

Have an issue you want prioritised? Comment below, or let us know on Discord.

## Task list

1.0.0 tagged issues can be found @ https://github.com/druxt/druxt.js/milestone/3

### Support / Bug fixes:

- [x] #464
- [x] #108
- [x] #51
- [x] #442 ***Windows only bug**
  - [x] #530 

### Enhancements / Development:

- [ ] #307
- [ ] #71
- [ ] #293
- [ ] #60
- [x] #349
- [x] #429

### Documentation: 

- [ ] https://github.com/druxt/demo.druxtjs.org/issues/427
  - [ ] https://github.com/druxt/demo.druxtjs.org/pull/428
  - https://app.feature-427-multilingual.demo-druxtjs-org.au2.amazee.io/
  - https://storybook.feature-427-multilingual.demo-druxtjs-org.au2.amazee.io/
- [ ] #501
- [ ] #198
  - [ ] #387
- [ ] https://github.com/druxt/druxt.js/issues/542
  - [ ] #172
- [ ] #330
- [ ] #458
- [x] #488 (May be redundant, as per #464)

Find more documentation issues @ https://github.com/druxt/druxt.js/issues?q=is%3Aissue+is%3Aopen+label%3Adocumentation

## Getting started

The Druxt Git repository is setup with [GitPod](https://gitpod.io) integration, all you need to do is open the following link, sign in or up (free, authentication with GitHub), and GitPod will set up your Druxt development environment:

https://gitpod.io#github.com/druxt/druxt.js
